
package isos.tutorial.isyiesd.cesvector.sertransactionmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITransactionManager", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITransactionManager {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "begin", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.Begin")
    @ResponseWrapper(localName = "beginResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.BeginResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/beginRequest", output = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/beginResponse")
    public String begin();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "commit", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.CommitResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/commitRequest", output = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/commitResponse")
    public void commit(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "rollback", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.RollbackResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/rollbackRequest", output = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/rollbackResponse")
    public void rollback(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "joinTransaction", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.JoinTransaction")
    @ResponseWrapper(localName = "joinTransactionResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager", className = "isos.tutorial.isyiesd.cesvector.sertransactionmanager.JoinTransactionResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/joinTransactionRequest", output = "http://iesd21.isos.isyiesd.cesvector.sertransactionmanager/ITransactionManager/joinTransactionResponse")
    public void joinTransaction(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

}
