
package isos.tutorial.isyiesd.cesvector.sertransactionmanager;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TransactionManagerService", targetNamespace = "http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", wsdlLocation = "http://localhost:2059/TransactionManager?wsdl")
public class TransactionManagerService
    extends Service
{

    private final static URL TRANSACTIONMANAGERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSACTIONMANAGERSERVICE_EXCEPTION;
    private final static QName TRANSACTIONMANAGERSERVICE_QNAME = new QName("http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", "TransactionManagerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2059/TransactionManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSACTIONMANAGERSERVICE_WSDL_LOCATION = url;
        TRANSACTIONMANAGERSERVICE_EXCEPTION = e;
    }

    public TransactionManagerService() {
        super(__getWsdlLocation(), TRANSACTIONMANAGERSERVICE_QNAME);
    }

    public TransactionManagerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSACTIONMANAGERSERVICE_QNAME, features);
    }

    public TransactionManagerService(URL wsdlLocation) {
        super(wsdlLocation, TRANSACTIONMANAGERSERVICE_QNAME);
    }

    public TransactionManagerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSACTIONMANAGERSERVICE_QNAME, features);
    }

    public TransactionManagerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionManagerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITransactionManager
     */
    @WebEndpoint(name = "TransactionManagerPort")
    public ITransactionManager getTransactionManagerPort() {
        return super.getPort(new QName("http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", "TransactionManagerPort"), ITransactionManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITransactionManager
     */
    @WebEndpoint(name = "TransactionManagerPort")
    public ITransactionManager getTransactionManagerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", "TransactionManagerPort"), ITransactionManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSACTIONMANAGERSERVICE_EXCEPTION!= null) {
            throw TRANSACTIONMANAGERSERVICE_EXCEPTION;
        }
        return TRANSACTIONMANAGERSERVICE_WSDL_LOCATION;
    }

}
