
package isos.tutorial.isyiesd.cesvector.sertwophaselockmanager;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITplm", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITplm {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "acquireLocks", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager", className = "isos.tutorial.isyiesd.cesvector.sertwophaselockmanager.AcquireLocks")
    @ResponseWrapper(localName = "acquireLocksResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager", className = "isos.tutorial.isyiesd.cesvector.sertwophaselockmanager.AcquireLocksResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager/ITplm/acquireLocksRequest", output = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager/ITplm/acquireLocksResponse")
    public boolean acquireLocks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "releaseLocks", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager", className = "isos.tutorial.isyiesd.cesvector.sertwophaselockmanager.ReleaseLocks")
    @ResponseWrapper(localName = "releaseLocksResponse", targetNamespace = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager", className = "isos.tutorial.isyiesd.cesvector.sertwophaselockmanager.ReleaseLocksResponse")
    @Action(input = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager/ITplm/releaseLocksRequest", output = "http://iesd21.isos.isyiesd.cesvector.sertwophaselockmanager/ITplm/releaseLocksResponse")
    public boolean releaseLocks(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
