
package isos.tutorial.isyiesd.cesvector.sertwophaselockmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TplmService", targetNamespace = "http://sertwophaselockmanager.cesvector.isyiesd.tutorial.isos/", wsdlLocation = "http://localhost:2060/Tplm?wsdl")
public class TplmService
    extends Service
{

    private final static URL TPLMSERVICE_WSDL_LOCATION;
    private final static WebServiceException TPLMSERVICE_EXCEPTION;
    private final static QName TPLMSERVICE_QNAME = new QName("http://sertwophaselockmanager.cesvector.isyiesd.tutorial.isos/", "TplmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2060/Tplm?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TPLMSERVICE_WSDL_LOCATION = url;
        TPLMSERVICE_EXCEPTION = e;
    }

    public TplmService() {
        super(__getWsdlLocation(), TPLMSERVICE_QNAME);
    }

    public TplmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TPLMSERVICE_QNAME, features);
    }

    public TplmService(URL wsdlLocation) {
        super(wsdlLocation, TPLMSERVICE_QNAME);
    }

    public TplmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TPLMSERVICE_QNAME, features);
    }

    public TplmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TplmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITplm
     */
    @WebEndpoint(name = "TplmPort")
    public ITplm getTplmPort() {
        return super.getPort(new QName("http://sertwophaselockmanager.cesvector.isyiesd.tutorial.isos/", "TplmPort"), ITplm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITplm
     */
    @WebEndpoint(name = "TplmPort")
    public ITplm getTplmPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sertwophaselockmanager.cesvector.isyiesd.tutorial.isos/", "TplmPort"), ITplm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TPLMSERVICE_EXCEPTION!= null) {
            throw TPLMSERVICE_EXCEPTION;
        }
        return TPLMSERVICE_WSDL_LOCATION;
    }

}
