
package isos.tutorial.isyiesd.cesvector.sertransactionmanager;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestService", targetNamespace = "http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", wsdlLocation = "http://localhost:2059/Test?wsdl")
public class TestService
    extends Service
{

    private final static URL TESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSERVICE_EXCEPTION;
    private final static QName TESTSERVICE_QNAME = new QName("http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", "TestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:2059/Test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSERVICE_WSDL_LOCATION = url;
        TESTSERVICE_EXCEPTION = e;
    }

    public TestService() {
        super(__getWsdlLocation(), TESTSERVICE_QNAME);
    }

    public TestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSERVICE_QNAME, features);
    }

    public TestService(URL wsdlLocation) {
        super(wsdlLocation, TESTSERVICE_QNAME);
    }

    public TestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSERVICE_QNAME, features);
    }

    public TestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITest
     */
    @WebEndpoint(name = "TestPort")
    public ITest getTestPort() {
        return super.getPort(new QName("http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", "TestPort"), ITest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITest
     */
    @WebEndpoint(name = "TestPort")
    public ITest getTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sertransactionmanager.cesvector.isyiesd.tutorial.isos/", "TestPort"), ITest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSERVICE_EXCEPTION!= null) {
            throw TESTSERVICE_EXCEPTION;
        }
        return TESTSERVICE_WSDL_LOCATION;
    }

}
